name: learn-github-actions
on: [push]

  group: deploy-to-neocities
  cancel-in-progress: true
jobs:
  check-bats-version:
    runs-on: 
      group: ubuntu-runners
    steps:
      - uses: actions/checkout@v4
      - run: upload.sh
